[package]
name = "subnet-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bend-lang = { git = "https://github.com/HigherOrderCO/Bend", branch = "main" }
dashmap = "5.5.0"
